name: docs

on:
  push:
    branches: ['master']
    paths: ['docs/**']

jobs:
  docs:
    name: "Generate docs"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: python -m pip install -r docs/requirements.txt

      - name: Generate docs
        run: mkdocs build

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
