name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: "Generate release"
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Build release package
        run: ./build-dist.sh

      - name: Copy release package
        run: cp /tmp/wp-open-events.zip wp-open-events-${{ github.ref_name }}.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: wp-open-events-${{ github.ref_name }}.zip
