name: Unit tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          cd js/src/components
          npm install

      - name: Run tests
        run: |
          cd js/src/components
          npm run test
